# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Audio Format file type mp3 or wav
  class AudioFormatEnum
    AUDIO_FORMAT_ENUM = [
      # mp3 file
      MP3 = 'mp3'.freeze,

      # wav file
      WAV = 'wav'.freeze
    ].freeze
  end
end
