# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Audio Direction
  class AudioDirectionEnum
    AUDIO_DIRECTION_ENUM = [
      # TODO: Write general description for IN
      IN = 'in'.freeze,

      # TODO: Write general description for OUT
      OUT = 'out'.freeze
    ].freeze
  end
end
