# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Error Structure Model
  class Errors < BaseModel
    # Error Description
    # @return [List of Error]
    attr_accessor :error

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['error'] = 'Error'
      @_hash
    end

    def initialize(error = nil)
      @error = error
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      error = nil
      unless hash['Error'].nil?
        error = []
        hash['Error'].each do |structure|
          error << (Error.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Errors.new(error)
    end
  end
end
