# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # GroupConfirmFile.
  class GroupConfirmFileEnum
    GROUP_CONFIRM_FILE_ENUM = [
      # mp3 file
      MP3 = 'mp3'.freeze,

      # wav file
      WAV = 'wav'.freeze
    ].freeze
  end
end
