# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # mActivate.
  class MActivateEnum
    M_ACTIVATE_ENUM = [
      # TODO: Write general description for ACTIVATE
      ACTIVATE = 1,

      # TODO: Write general description for DEACTIVATE
      DEACTIVATE = 0
    ].freeze
  end
end
