# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # MergeNumber.
  class MergeNumberEnum
    MERGE_NUMBER_ENUM = [
      # TODO: Write general description for DELETE
      DELETE = 0,

      # TODO: Write general description for MERGE
      MERGE = 1
    ].freeze
  end
end
