# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # PlayDtmfDirection.
  class PlayDtmfDirectionEnum
    PLAY_DTMF_DIRECTION_ENUM = [
      # in direction
      IN = 'in'.freeze,

      # out direction
      OUT = 'out'.freeze,

      # both
      BOTH = 'both'.freeze
    ].freeze
  end
end
