# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # ProductCode27.
  class ProductCode27Enum
    PRODUCT_CODE27_ENUM = [
      # TODO: Write general description for ALL
      ALL = 0,

      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2,

      # TODO: Write general description for ENUM_3
      ENUM_3 = 3,

      # TODO: Write general description for ENUM_4
      ENUM_4 = 4,

      # TODO: Write general description for TRANSCRIPTION
      TRANSCRIPTION = 5,

      # TODO: Write general description for EMAIL
      EMAIL = 6,

      # TODO: Write general description for CONFERENCE
      CONFERENCE = 7,

      # TODO: Write general description for CARRIER
      CARRIER = 8,

      # TODO: Write general description for ENUM_9
      ENUM_9 = 9,

      # TODO: Write general description for ENUM_10
      ENUM_10 = 10,

      # TODO: Write general description for ENUM_11
      ENUM_11 = 11,

      # TODO: Write general description for ENUM_12
      ENUM_12 = 12,

      # TODO: Write general description for ENUM_13
      ENUM_13 = 13
    ].freeze
  end
end
