# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Status24.
  class Status24Enum
    STATUS24_ENUM = [
      # Interrupt Call will be cancel
      CANCELED = 'canceled'.freeze,

      # Interrupt Call is complete
      COMPLETED = 'completed'.freeze
    ].freeze
  end
end
