# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Transcription Status
  class StatusEnum
    STATUS_ENUM = [
      # TODO: Write general description for INPROGRESS
      INPROGRESS = 'inprogress'.freeze,

      # TODO: Write general description for SUCCESS
      SUCCESS = 'success'.freeze,

      # TODO: Write general description for FAILURE
      FAILURE = 'failure'.freeze
    ].freeze
  end
end
