# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApi
  # Type.
  class TypeEnum
    TYPE_ENUM = [
      # Email send as text format
      TEXT = 'text'.freeze,

      # Email send as HTML format
      HTML = 'html'.freeze
    ].freeze
  end
end
