# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class LetterControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.letter
  end

  # Retrieve a list of letter objects. The letter objects are sorted by creation date, with the most recently created letters appearing first.
  def test_test_list_letters()
    # Parameters for the API call
    page = nil
    pagesize = nil
    lettersid = nil
    date_created = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_letters(page, pagesize, lettersid, date_created)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

end
