# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class ShortCodeControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.short_code
  end

  # Retrieve a list of Short Code assignment associated with your Ytel account.
  def test_test_list_shortcodes()
    # Parameters for the API call
    shortcode = nil
    page = nil
    pagesize = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_shortcodes(shortcode, page, pagesize)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

  # Retrieve a list of Short Code messages.
  def test_test_list_sms()
    # Parameters for the API call
    shortcode = nil
    to = nil
    date_sent = nil
    page = nil
    page_size = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_sms(shortcode, to, date_sent, page, page_size)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

  # Retrive a list of inbound Sms Short Code messages associated with your Ytel account.
  def test_test_list_inbound_sms()
    # Parameters for the API call
    page = nil
    pagesize = nil
    from = nil
    shortcode = nil
    datecreated = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_inbound_sms(page, pagesize, from, shortcode, datecreated)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

end
