# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class TranscriptionControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.transcription
  end

  # Retrieve a list of transcription objects for your Ytel account.
  def test_test_list_transcriptions()
    # Parameters for the API call
    page = nil
    pagesize = nil
    status = nil
    date_transcribed = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_transcriptions(page, pagesize, status, date_transcribed)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

end
