# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class PhoneNumberControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.phone_number
  end

  # Retrieve a list of purchased phones numbers associated with your Ytel account.
  def test_test_list_numbers()
    # Parameters for the API call
    page = nil
    page_size = nil
    number_type = nil
    friendly_name = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_numbers(page, page_size, number_type, friendly_name)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

end
