# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class RecordingControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.recording
  end

  # Retrieve a list of recording objects.
  def test_test_list_recordings()
    # Parameters for the API call
    page = nil
    pagesize = nil
    datecreated = nil
    callsid = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_recordings(page, pagesize, datecreated, callsid)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

end
