# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class PostCardControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.post_card
  end

  # Retrieve a list of postcard objects. The postcards objects are sorted by creation date, with the most recently created postcards appearing first.
  def test_test_list_postcards()
    # Parameters for the API call
    page = nil
    pagesize = nil
    postcardid = nil
    date_created = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_postcards(page, pagesize, postcardid, date_created)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

end
