# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class CarrierControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.carrier
  end

  # Retrieve a list of carrier lookup objects.
  def test_test_carrier_results()
    # Parameters for the API call
    page = nil
    page_size = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_carrier_results(page, page_size)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

end
