# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class CallControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.call
  end

  # A list of calls associated with your Ytel account
  def test_test_list_calls()
    # Parameters for the API call
    page = nil
    page_size = nil
    to = nil
    from = nil
    date_created = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_calls(page, page_size, to, from, date_created)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

end
