# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class EmailControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def self.startup
    self.controller = @@api_client.email
  end

  # Retrieve a list of emails that have been blocked.
  def test_test_blocked_emails()
    # Parameters for the API call
    offset = nil
    limit = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_blocked_emails(offset, limit)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

  # Retrieve a list of emails that are on the spam list.
  def test_test_spam_emails()
    # Parameters for the API call
    offset = nil
    limit = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_spam_emails(offset, limit)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

  # Retrieve a list of emails that have bounced.
  def test_test_bounced_emails()
    # Parameters for the API call
    offset = nil
    limit = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_bounced_emails(offset, limit)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

  # Retrieve a list of invalid email addresses.
  def test_test_invalid_emails()
    # Parameters for the API call
    offset = nil
    limit = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_invalid_emails(offset, limit)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

  # Retrieve a list of email addresses from the unsubscribe list.
  def test_test_list_unsubscribed_emails()
    # Parameters for the API call
    offset = nil
    limit = nil

    # Perform the API call through the SDK function
    result = self.class.controller.create_list_unsubscribed_emails(offset, limit)

    # Test response code
    assert_equal(@response_catcher.response.status_code, 200)
  end

end
