# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Choose account status either 0 or 1
  class ActivateStatusEnum
    ACTIVATE_STATUS_ENUM = [
      # TODO: Write general description for MACTIVATE
      MACTIVATE = 1,

      # TODO: Write general description for DEACTIVATE
      DEACTIVATE = 0
    ].freeze
  end
end
