# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Audio Direction
  class AudioDirection29Enum
    AUDIO_DIRECTION29_ENUM = [
      # TODO: Write general description for IN
      IN = 'in'.freeze,

      # TODO: Write general description for OUT
      OUT = 'out'.freeze
    ].freeze
  end
end
