# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # The direction the audio effect should be placed on. If IN, the effects will
  # occur on the incoming audio stream. If OUT, the effects will occur on the
  # outgoing audio stream.
  class AudioDirectionEnum
    AUDIO_DIRECTION_ENUM = [
      # TODO: Write general description for ENUM_IN
      ENUM_IN = 'in'.freeze,

      # TODO: Write general description for OUT
      OUT = 'out'.freeze
    ].freeze
  end
end
