# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # The URL for the audio file that is to be played during the conference.
  # Multiple audio files can be chained by using a semicolon.
  class AudioUrlEnum
    AUDIO_URL_ENUM = [
      # TODO: Write general description for MP3
      MP3 = 'mp3'.freeze,

      # TODO: Write general description for WAV
      WAV = 'wav'.freeze
    ].freeze
  end
end
