# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # AudioUrl43.
  class AudioUrl43Enum
    AUDIO_URL43_ENUM = [
      # mp3 file
      MP3 = 'mp3'.freeze,

      # wav file
      WAV = 'wav'.freeze
    ].freeze
  end
end
