# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Play DTMF Direction & in play audio & sendDigit
  class Direction23Enum
    DIRECTION23_ENUM = [
      # in direction
      IN = 'in'.freeze,

      # out direction
      OUT = 'out'.freeze,

      # both
      BOTH = 'both'.freeze
    ].freeze
  end
end
