# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # The leg of the call to record
  class Direction4Enum
    DIRECTION4_ENUM = [
      # TODO: Write general description for ENUM_IN
      ENUM_IN = 'in'.freeze,

      # TODO: Write general description for OUT
      OUT = 'out'.freeze,

      # TODO: Write general description for BOTH
      BOTH = 'both'.freeze
    ].freeze
  end
end
