# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Fileformat37.
  class Fileformat37Enum
    FILEFORMAT37_ENUM = [
      # mp3 file
      MP3 = 'mp3'.freeze,

      # wav file
      WAV = 'wav'.freeze
    ].freeze
  end
end
