# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Specify the audio file you want to play when the called party picks up the
  # call
  class GroupConfirmFileEnum
    GROUP_CONFIRM_FILE_ENUM = [
      # TODO: Write general description for MP3
      MP3 = 'mp3'.freeze,

      # TODO: Write general description for WAV
      WAV = 'wav'.freeze
    ].freeze
  end
end
