# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Types Of Method
  class HttpActionEnum
    HTTP_ACTION_ENUM = [
      # Get type
      GET = 'GET'.freeze,

      # Post Type
      POST = 'POST'.freeze
    ].freeze
  end
end
