# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # How Ytel should handle the receiving numbers voicemail machine
  class IfMachineEnum
    IF_MACHINE_ENUM = [
      # TODO: Write general description for CONTINUE
      CONTINUE = 'continue'.freeze,

      # TODO: Write general description for HANGUP
      HANGUP = 'hangup'.freeze
    ].freeze
  end
end
