# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # How Message360 should handle the receiving numbers voicemail machine
  class IfMachine32Enum
    IF_MACHINE32_ENUM = [
      # TODO: Write general description for CONTINUE
      CONTINUE = 'continue'.freeze,

      # TODO: Write general description for HANGUP
      HANGUP = 'hangup'.freeze
    ].freeze
  end
end
