# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Interrupted Call Status
  class InterruptedCallStatusEnum
    INTERRUPTED_CALL_STATUS_ENUM = [
      # Interrupt Call will be cancel
      CANCELED = 'canceled'.freeze,

      # Interrupt Call is complete
      COMPLETED = 'completed'.freeze
    ].freeze
  end
end
