# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # 0 to suspend or 1 to activate
  class MActivateEnum
    M_ACTIVATE_ENUM = [
      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_0
      ENUM_0 = 0
    ].freeze
  end
end
