# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # MergeNumber40.
  class MergeNumber40Enum
    MERGE_NUMBER40_ENUM = [
      # TODO: Write general description for DELETE
      DELETE = 0,

      # TODO: Write general description for MERGE
      MERGE = 1
    ].freeze
  end
end
