# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # 0 to delete or 1 to merge numbers to parent account.
  class MergeNumberEnum
    MERGE_NUMBER_ENUM = [
      # TODO: Write general description for ENUM_0
      ENUM_0 = 0,

      # TODO: Write general description for ENUM_1
      ENUM_1 = 1
    ].freeze
  end
end
