# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Choose sub account either merge or delete
  class MergeNumberStatusEnum
    MERGE_NUMBER_STATUS_ENUM = [
      # TODO: Write general description for DELETE
      DELETE = 0,

      # TODO: Write general description for MERGE
      MERGE = 1
    ].freeze
  end
end
