# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # The capability the number supports.
  class NumberType15Enum
    NUMBER_TYPE15_ENUM = [
      # TODO: Write general description for ALL
      ALL = 'all'.freeze,

      # TODO: Write general description for VOICE
      VOICE = 'voice'.freeze,

      # TODO: Write general description for SMS
      SMS = 'sms'.freeze
    ].freeze
  end
end
