# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Phone Number Type All,SMS or Voice
  class NumberType24Enum
    NUMBER_TYPE24_ENUM = [
      # Get all phone Number type
      ALL = 'all'.freeze,

      # Get only voice number type
      VOICE = 'voice'.freeze,

      # Get Only SMs number type
      SMS = 'sms'.freeze
    ].freeze
  end
end
