# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Transcription Status
  class Status25Enum
    STATUS25_ENUM = [
      # TODO: Write general description for INPROGRESS
      INPROGRESS = 'inprogress'.freeze,

      # TODO: Write general description for SUCCESS
      SUCCESS = 'success'.freeze,

      # TODO: Write general description for FAILURE
      FAILURE = 'failure'.freeze
    ].freeze
  end
end
