# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Status to set the in-progress call to
  class StatusEnum
    STATUS_ENUM = [
      # TODO: Write general description for CANCELED
      CANCELED = 'canceled'.freeze,

      # TODO: Write general description for COMPLETED
      COMPLETED = 'completed'.freeze
    ].freeze
  end
end
