# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # The state of the transcription.
  class Status12Enum
    STATUS12_ENUM = [
      # TODO: Write general description for INPROGRESS
      INPROGRESS = 'inprogress'.freeze,

      # TODO: Write general description for SUCCESS
      SUCCESS = 'success'.freeze,

      # TODO: Write general description for FAILURE
      FAILURE = 'failure'.freeze
    ].freeze
  end
end
