# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Specifies the type of email to be sent
  class TypeEnum
    TYPE_ENUM = [
      # TODO: Write general description for TEXT
      TEXT = 'text'.freeze,

      # TODO: Write general description for HTML
      HTML = 'html'.freeze
    ].freeze
  end
end
