# ytel_apiv3
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module YtelApiv3
  # Type36.
  class Type36Enum
    TYPE36_ENUM = [
      # Email send as text format
      TEXT = 'text'.freeze,

      # Email send as HTML format
      HTML = 'html'.freeze
    ].freeze
  end
end
